---
version: '2'

services:
  app:
    image: node:10.4-alpine
    volumes:
        - .:/usr/src/app
    ports:
        - "3000:3000"
    working_dir: /usr/src/app
    command: ["npm", "start"]
    environment:
      - PORT=3000
      - REDIS_URL=redis

  redis:
    image: "redis:latest"